steps:
  # Pull the latest image to use as cache
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - "-c"
      - >-
        docker pull gcr.io/$PROJECT_ID/crypto-top-coins:latest
        || exit 0
    id: PullLatest
  # Build the container images
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/crypto-top-coins:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/crypto-top-coins:latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/crypto-top-coins:latest"
      - "."
    id: Build
  # Push the container images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/crypto-top-coins:$COMMIT_SHA"]
    id: Push
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/crypto-top-coins:latest"]
    id: PushLatest
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "crypto-top-coins"
      - "--image"
      - "gcr.io/$PROJECT_ID/crypto-top-coins:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    id: Deploy
images:
  - "gcr.io/$PROJECT_ID/crypto-top-coins:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/crypto-top-coins:latest"
