name: CMC Scrapper Job

on:
  workflow_dispatch:

jobs:
  run:
    name: run and commit new data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      working-directory: ./cmc-scrapper
    - name: Get CMC Data
      run: node app.js
      working-directory: ./cmc-scrapper
    - name: Commit New Data
      uses: EndBug/add-and-commit@v9
      with:
        add: './server/data/cmc-data.json'
