name: CMC Scrapper Job

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      working-directory: ./cmc-scrapper
    - name: Get CMC Data
      run: node app.js
      working-directory: ./cmc-scrapper
    - name: Commit New Data
      uses: EndBug/add-and-commit@v9
      with:
        add: './server/data/cmc-data.json'
